export const MOVIES_LOADING = "MOVIES_LOADING";
export const MOVIES_LOAD_ERROR = "MOVIES_LOAD_ERROR";
export const MOVIES_LOAD_SUCCESS = "MOVIES_LOAD_SUCCESS";

export const GENRES_LOADING = "GENRES_LOADING";
export const GENRES_LOAD_ERROR = "GENRES_LOAD_ERROR";
export const GENRES_LOAD_SUCCESS = "GENRES_LOAD_SUCCESS";

export const MOVIES_RATING_UPDATE = "MOVIES_RATING_UPDATE";
export const GENRE_TOGGLE = "GENRES_TOGGLE";
